---
# EdOps 基础配置变量（随机生成的安全值）
EDOPS_MYSQL_ROOT_PASSWORD: "{{ 12|random_string }}"
EDOPS_RABBITMQ_DEFAULT_PASS: "{{ 12|random_string }}"
EDOPS_MINIO_ROOT_PASSWORD: "{{ 12|random_string }}"
EDOPS_ISPOT_APP_SOURCE: "{{ 64|random_string }}"

# Nacos 基础配置变量（随机生成的安全值）
EDOPS_ELASTICSEARCH_PASSWORD: "{{ 12|random_string }}"
EDOPS_TENANT_SECRET_KEY: "{{ 64|random_string }}"
EDOPS_MQTT_PASSWORD: "{{ 12|random_string }}"
EDOPS_MQTT_ACCOUNT_PASSWORD: "{{ 12|random_string }}"
