version: "3"
services:

  ############# Portainer: container supervision with a web UI
  portainer:
    image: portainer/portainer:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
    restart: unless-stopped
    depends_on:
      - nginx
