---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- k8s/namespace.yml
- k8s/deployments.yml
- k8s/ingress.yml
- k8s/services.yml
- k8s/volumes.yml

# namespace to deploy all Resources to
namespace: {{ K8S_NAMESPACE }}

# labels added to all Resources
# https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
commonLabels:
  app.kubernetes.io/instance: openedx-{{ ID }}
  app.kubernetes.io/version: {{ TUTOR_VERSION }}
  app.kubernetes.io/part-of: openedx
  app.kubernetes.io/managed-by: tutor

configMapGenerator:
- name: openedx-settings-lms
  files:{% for file in "apps/openedx/settings/lms"|walk_templates %}
  - {{ file }}{% endfor %}
- name: openedx-settings-cms
  files:{% for file in "apps/openedx/settings/cms"|walk_templates %}
  - {{ file }}{% endfor %}
- name: openedx-config
  files:{% for file in "apps/openedx/config"|walk_templates %}
  - {{ file }}{% endfor %}
- name: nginx-config
  files:{% for file in "apps/nginx"|walk_templates %}
  - {{ file }}{% endfor %}
{% if ACTIVATE_MYSQL %}- name: mysql-config
  env: apps/mysql/auth.env{% endif %}
{{ patch("kustomization-configmapgenerator") }}
