SITE_NAME: "{{ LMS_HOST }}"
BOOK_URL: ""
LOG_DIR: "/openedx/data/logs"
LOGGING_ENV: "sandbox"
OAUTH_OIDC_ISSUER: "{{ JWT_COMMON_ISSUER }}"
PLATFORM_NAME: "{{ PLATFORM_NAME }}"
FEATURES:
  {{ patch("common-env-features")|indent(2) }}
  {{ patch("lms-env-features")|indent(2) }}
  CERTIFICATES_HTML_VIEW: true
  PREVIEW_LMS_BASE: "{{ PREVIEW_LMS_HOST }}"
  ENABLE_COURSE_DISCOVERY: true
  ENABLE_COURSEWARE_SEARCH: true
  ENABLE_CSMH_EXTENDED: false
  ENABLE_DASHBOARD_SEARCH:  true
  ENABLE_COMBINED_LOGIN_REGISTRATION: true
  ENABLE_GRADE_DOWNLOADS: true
  ENABLE_LEARNER_RECORDS: false
  ENABLE_MOBILE_REST_API: true
  ENABLE_OAUTH2_PROVIDER: true
  ENABLE_PREREQUISITE_COURSES: true
  ENABLE_THIRD_PARTY_AUTH: true
  MILESTONES_APP: true
LMS_ROOT_URL: "{{ "https" if ENABLE_HTTPS else "http" }}://{{ LMS_HOST }}"
CMS_ROOT_URL: "{{ "https" if ENABLE_HTTPS else "http" }}://{{ CMS_HOST }}"
CMS_BASE: "{{ CMS_HOST }}"
LMS_BASE: "{{ LMS_HOST }}"
CONTACT_EMAIL: "{{ CONTACT_EMAIL }}"
CELERY_BROKER_TRANSPORT: "redis"
CELERY_BROKER_HOSTNAME: "{{ REDIS_HOST }}:{{ REDIS_PORT }}"
CELERY_BROKER_VHOST: "{{ OPENEDX_CELERY_REDIS_DB }}"
CELERY_BROKER_USER: "{{ REDIS_USERNAME }}"
CELERY_BROKER_PASSWORD: "{{ REDIS_PASSWORD }}"
ALTERNATE_WORKER_QUEUES: "cms"
ENABLE_COMPREHENSIVE_THEMING: true
EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST: "{{ SMTP_HOST }}"
EMAIL_PORT: {{ SMTP_PORT }}
EMAIL_USE_TLS: {{ "true" if SMTP_USE_TLS else "false" }}
ACE_ROUTING_KEY: "edx.lms.core.default"
HTTPS: "{{ "on" if ENABLE_HTTPS else "off" }}"
LANGUAGE_CODE: "{{ LANGUAGE_CODE }}"
SESSION_COOKIE_DOMAIN: "{{ LMS_HOST }}"
{{ patch("lms-env") }}
{% include "apps/openedx/config/partials/auth.yml" %}
